mysitetest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('index', views.index, name='index'),
    path('bill', views.add_bill, name='bill'),
    path('billtest', views.add_billtest, name='billtest'),
    path('', views.dashboard, name='dashboard'),
    path('add_customer', views.add_customer, name='add_customer'),
    path('add_product_packing', views.add_product_packing, name='add_product_packing'),
    path('add_product', views.add_product, name='add_product'),
    path('add_product_ingredient', views.add_product_ingredient, name='add_product_ingredient'),
    path('add_product_hsn_code', views.add_product_hsn_code, name='add_product_hsn_code'),
    path('add_product_batch', views.add_product_batch, name='add_product_batch'),
    path('edit_customer/<int:pk>', views.edit_customer, name='edit_customer'),
    path('edit_ingredient/<int:pk>', views.edit_ingredient, name='edit_ingredient'),
    path('edit_hsn_code/<int:pk>', views.edit_hsn_code, name='edit_hsn_code'),
    path('edit_product_packing/<int:pk>', views.edit_product_packing, name='edit_product_packing'),
    path('edit_product/<int:pk>', views.edit_product, name='edit_product'),
    path('edit_product_batch/<int:pk>', views.edit_product_batch, name='edit_product_batch'),
    path('delete_ingredient/<int:pk>', views.delete_ingredient, name='delete_ingredient'),
    path('delete_hsn_code/<int:pk>', views.delete_hsn_code, name='delete_hsn_code'),
    path('delete_customers/<int:pk>', views.delete_customers, name='delete_customers'),
    path('delete_product_batch/<int:pk>', views.delete_product_batch, name='delete_product_batch'),
    path('delete_product_packing/<int:pk>', views.delete_product_packing, name='delete_product_packing'),
    path('delete_product/<int:pk>', views.delete_product, name='delete_product'),
    path('delete_order/<int:pk>', views.delete_order, name='delete_order'),
    path('customers', views.customers, name='customers'),
    path('product_packing', views.product_packing, name='product_packing'),
    path('product_detail_view/<int:product_id>', views.product_detail_view, name='product_detail_view'),
    path('product', views.product, name='product'),
    path('product_ingredient', views.product_ingredient, name='product_ingredient'),
    path('product_hsn_code', views.product_hsn_code, name='product_hsn_code'),
    path('product_batch', views.product_batch, name='product_batch'),
    path('expired_product', views.expired_product, name='expired_product'),
    path('show/<int:purchaseno>', views.show, name='show'),
    path('edit/<int:purchaseno>/<int:customer_id>', views.edit_billtest_final, name='edit'),
]

shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from .models import Product,ProductDetailBatch,CustomerDetail,Bill,BillItems,BillItemsTest, BillTest2, BillItemsTest2,Ingredient, ProductBatch,HSNCode
from .forms import BillForm,BillItemsForm,BillItemsFormset,BillItemsFormsetTest, CustomerDetailForm,ProductDetailBatchForm, IngredientForm, ProductForm, ProductBatchForm,HSNCodeForm


def index(request):
    products_list = ProductDetailBatch.objects.all()
    customers_list = CustomerDetail.objects.all()
    bills_list = BillTest2.objects.select_related().all()
    bill_items = BillItemsTest2.objects.select_related().all()
    context = {'products_list': products_list, 'customers_list': customers_list, 'bills_list': bills_list, 'bill_items': bill_items}
    return render(request, 'shop/index.html', context)


# from django.forms.formsets import formset_factory

def add_bill(request):
    # BillItemsFormSet = formset_factory(BillItemsForm, extra=1, min_num=1, validate_min=True)
    customers_list = CustomerDetail.objects.all()
    if request.method == 'POST':
        form = BillForm(request.POST)
        formset = BillItemsFormset(request.POST)
        if all([form.is_valid(), formset.is_valid()]):
            bill = form.save()
            for inline_form in formset:
                if inline_form.cleaned_data:
                    billitems = inline_form.save(commit=False)
                    billitems.purchaseno = bill
                    billitems.save()
            return redirect('shop:index')
        else:
            print('form is not valid',form,formset)
    else:
        form = BillForm(request.GET or None)
        formset = BillItemsFormset(queryset=BillItems.objects.none())

    return render(request, 'shop/add_bill.html', {'form': form,
                                                   'formset': formset, 'customers': customers_list})

def add_billtest(request):
    # BillItemsFormSet = formset_factory(BillItemsForm, extra=1, min_num=1, validate_min=True)
    customers_list = CustomerDetail.objects.all()
    if request.method == 'POST':
        form = BillForm(request.POST)
        formset = BillItemsFormsetTest(request.POST)
        if all([form.is_valid(), formset.is_valid()]):
            bill = form.save()
            products_list = ProductDetailBatch.objects.all()
            purchase_no = -1
            for inline_form in formset:
                if inline_form.cleaned_data:
                    billitems = inline_form.save(commit=False)
                    billitems.purchaseno = bill
                    purchase_no = billitems.purchaseno.purchaseno
                    isFound = False
                    pro_pk = 0
                    print('purchaseno:',billitems.purchaseno,'billitems:',billitems.productName, 'productList:', products_list)
                    for pro in products_list:
                        if pro == billitems.productName and pro.quantity >= billitems.productQuantity:
                            isFound = True
                            pro_pk = pro.pk
                            print('isFound:True', 'pro_pk:', pro_pk)
                            billitems.productBatch = pro.batch_no.batch_no
                            billitems.productPacking = pro.packing
                            billitems.productPrice = pro.price
                            billitems.productTotalPrice = float(pro.price) * int(billitems.productQuantity)
                            break
                    if isFound:
                        productObj = ProductDetailBatch.objects.get(pk = pro_pk)
                        productObj.quantity -= billitems.productQuantity
                        print('productObj:', productObj, productObj.quantity)
                        billitems.save()
                        productObj.save()
                    else:
                        billObj = BillTest2.objects.get(purchaseno=bill.purchaseno)
                        billObj.delete()
                        return redirect('shop:product_packing')
            return redirect('shop:show', purchase_no)
        else:
            print('form is not valid',form,formset)
    else:
        form = BillForm(request.GET or None)
        formset = BillItemsFormsetTest(queryset=BillItems.objects.none())

    return render(request, 'shop/add_bill.html', {'form': form,
                                                   'formset': formset, 'customers': customers_list})


def show(request,purchaseno):
    bills_list = BillTest2.objects.select_related().all().filter(purchaseno=purchaseno)
    bill_items = BillItemsTest2.objects.select_related().all().filter(purchaseno=purchaseno)
    totalamount = 0
    totalamount_without_tax = 0
    total_tax = 0
    from .templatetags.calculate_tax import without_tax, tax
    for item in bill_items:
        totalamount += item.productTotalPrice
        totalamount_without_tax += without_tax(item.productTotalPrice, item.productName.batch_no.product.hsn_code.rate)
        total_tax += tax(item.productTotalPrice, item.productName.batch_no.product.hsn_code.rate)

    context = {'bills_list': bills_list, 'bill_items': bill_items, 'totalamount': totalamount, 'totalamount_without_tax': totalamount_without_tax, 'total_tax': total_tax}
    return render(request, 'shop/show.html', context)

def edit_billtest(request, purchaseno,customer_id):
    # BillItemsFormSet = formset_factory(BillItemsForm, extra=1, min_num=1, validate_min=True)
    bills = BillTest2.objects.get(purchaseno=purchaseno)
    bill_items = BillItemsTest2.objects.select_related().all().filter(purchaseno=purchaseno)
    customers_list = CustomerDetail.objects.all()
    if request.method == 'POST':
        form = BillForm(request.POST, instance = bills)
        formset = BillItemsFormsetTest(request.POST, queryset=bill_items)
        if all([form.is_valid(), formset.is_valid()]):
            bill = form.save()
            products_list = ProductDetailBatch.objects.all()
            purchase_no = -1
            for inline_form in formset:
                if inline_form.cleaned_data:
                    billitems = inline_form.save(commit=False)
                    billitems.purchaseno = bill
                    purchase_no = billitems.purchaseno.purchaseno
                    print('purchaseno:',billitems.purchaseno,'billitems:',billitems.productName, 'productList:', products_list)
                    for pro in products_list:
                        if pro == billitems.productName:
                            billitems.productBatch = pro.batch_no.batch_no
                            billitems.productPacking = pro.packing
                            billitems.productPrice = pro.price
                            billitems.productTotalPrice = float(pro.price) * int(billitems.productQuantity)
                            break
                    billitems.save()
            return redirect('shop:show', purchase_no)
        else:
            print('form is not valid',form.errors,formset.errors)
    else:
        form = BillForm(instance = bills)
        formset = BillItemsFormsetTest(queryset=bill_items)

    return render(request, 'shop/edit_bill.html', {'form': form,
                                                   'formset': formset, 'customers': customers_list})

def dashboard(request):
    total_product = Product.objects.count()
    total_buyer = CustomerDetail.objects.count()
    total_order = BillTest2.objects.count()
    orders = BillTest2.objects.select_related().all().order_by('-purchaseno')
    from datetime import date
    expired = ProductBatch.objects.all().filter(expirydate__lte = date.today()).count()
    context = {
        'product': total_product,
        'buyer': total_buyer,
        'order': total_order,
        'orders': orders,
        'expired': expired
    }
    return render(request, 'shop/dashboard.html', context)

def add_customer(request):
    if request.method == 'POST':
        form = CustomerDetailForm(request.POST)
        if form.is_valid():
            customer = form.save()
            return redirect('shop:dashboard')
        else:
            print('form is not valid',form)
    else:
        form = CustomerDetailForm(request.GET or None)
    return render(request, 'shop/add_customer.html', {'form': form, 'btn_add_edit': 'Create'})

def customers(request):
    customers_list = CustomerDetail.objects.all()
    context = {'customers_list': customers_list}
    return render(request, 'shop/view_customer.html', context)

def edit_customer(request, pk):
    customer = CustomerDetail.objects.get(pk=pk)
    if request.method == 'POST':
        form = CustomerDetailForm(request.POST,instance = customer)
        if form.is_valid():
            customer = form.save()
            return redirect('shop:customers')
        else:
            print('form is not valid',form)
    else:
        form = CustomerDetailForm(instance = customer)
    return render(request, 'shop/add_customer.html', {'form': form, 'btn_add_edit': 'Update'})

def product_packing(request):
    products_list = ProductDetailBatch.objects.all()
    context = {'products_list': products_list}
    return render(request, 'shop/view_products_packing.html', context)

def add_product_packing(request):
    if request.method == 'POST':
        form = ProductDetailBatchForm(request.POST)
        if form.is_valid():
            product = form.save()
            return redirect('shop:product_packing')
        else:
            print('form is not valid',form)
    else:
        form = ProductDetailBatchForm(request.GET or None)
    return render(request, 'shop/add_product_packing.html', {'form': form, 'btn_add_edit': 'Create'})

def edit_product_packing(request, pk):
    productbatch = ProductDetailBatch.objects.get(pk=pk)
    if request.method == 'POST':

shop/templates/shop/dashboard.html
{% extends 'base/base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
    <!-- Widgets  -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-1">
                            <i class="fa fa-cart-plus"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count">{{ order }}</span></div>
                                <div class="stat-heading">Order</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <a href="{% url 'shop:product' %}">
            <div class="card">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-2">
                            <i class="fa fa-product-hunt"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count">{{ product }}</span></div>
                                <div class="stat-heading">Product</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </a>
        </div>


        <div class="col-lg-3 col-md-6">
            <a href="{% url 'shop:customers' %}">
            <div class="card">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-4">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count">{{ buyer }}</span></div>
                                <div class="stat-heading">Customer</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </a>
        </div>

        <div class="col-lg-3 col-md-6">
            <a href="{% url 'shop:expired_product' %}">
            <div class="card">
                <div class="card-body">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-7">
                            <i class="fa fa-product-hunt"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count">{{ expired }}</span></div>
                                <div class="stat-heading">Expired Product Batch</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </a>
        </div>
    </div>
    <!-- /Widgets -->
    
    <div class="clearfix"></div>

    <!-- Orders -->
    <div class="orders">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Orders </h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th class="serial">#</th>
                                        <th>Purchase No.</th>
                                        <th>Customer Name</th>
                                        <th>Purchase Date</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if orders %}
                                    {% for order in orders %}
                                    <tr>
                                        <td class="serial">{{ forloop.counter }}</td>
                                        <td>{{ order.purchaseno }}</td>
                                        <td>{{ order.customer.name }}</td>
                                        <td>{{ order.purchase_date }}</td>
                                        
                                        <td>
                                            <a class="btn btn-primary" href="{% url 'shop:edit' order.purchaseno  order.customer_id %}" >Edit</a>
                                            <a class="btn btn-danger" href="{% url 'shop:delete_order' order.purchaseno %}" onclick="return confirm('Are you sure you want to delete this?')" >Delete</a>
                                            
                                            <a class="btn btn-primary" href="{% url 'shop:show' order.purchaseno %}" ><i class="md md-print"></i>Print</a>
                                            
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                        <tr><td>No Order Data</td></tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div> <!-- /.table-stats -->
                    </div>
                </div> <!-- /.card -->
            </div>  <!-- /.col-lg-8 -->

            
        </div>
    </div>
    <!-- /.orders -->
{% endblock content %}

shop/templates/shop/view_product_hsn_code.html
{% extends 'base/base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">HSN Code  <button type="button" class="btn" style="color:white; "><a href="{% url 'shop:add_product_hsn_code' %}"> Add New +</a> </button> </h4>
                    
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">#</th>
                                    <th>HSN Code</th>
                                    <th>Rate</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if hsn_code_list %}
                                {% for hsn_code in hsn_code_list %}
                                <tr>
                                    <td class="serial">{{ forloop.counter }}</td>
                                    <td>{{ hsn_code.hsn_code }}</td>
                                    <td>{{ hsn_code.rate }}</td>
                                    
                                    <td>
                                        <a class="btn btn-primary" href="{% url 'shop:edit_hsn_code' hsn_code.pk %}" >Edit</a>
                                        <a class="btn btn-danger" href="{% url 'shop:delete_hsn_code' hsn_code.pk %}" onclick="return confirm('Are you sure you want to delete this?')" >Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                    <tr><td>No HSN Code Data</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
        </div>  <!-- /.col-lg-8 -->

        
    </div>
</div>
{% endblock content %}

shop/templates/shop/view_products_batch.html
{% extends 'base/base.html' %}
{% load calculate_tax %}
{% block title %}Dashboard{% endblock title %}

{% block content %}
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Batch <button type="button" class="btn" style="color:white; "><a href="{% url 'shop:add_product_batch' %}"> Add New +</a> </button> </h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">#</th>
                                    <th>Product</th>
                                    <th>Batch No.</th>
                                    <th>Manufacturing Date</th>
                                    <th>Expiry Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if products_list %}
                                {% for product in products_list %}
                                <tr>
                                    <td class="serial">{{ forloop.counter }}</td>
                                    <td>{{ product.product }}</td>
                                    <td>{{ product.batch_no }}</td>
                                    <td>{{ product.mfgdate }}</td>
                                    <td>{{ product.expirydate }}</td>
                                   
                                    <td>
                                        {% if product.expirydate <= today %}
                                        <a class="btn btn-danger" href="#">Expired</a>
                                        {% elif product.expirydate <= today30 %}
                                        <a class="btn btn-primary" title="Products expiring within a month" style="background-color: yellow; color:black;" href="#">Expiring Soon in {% count_days product.expirydate today as daysleft %} {% if daysleft == 1 %} 1 day {% else %} {{daysleft}} days {% endif %} </a>
                                        {% endif %}
                                        <a class="btn btn-primary" href="{% url 'shop:edit_product_batch' product.pk %}" >Edit</a>
                                        <a class="btn btn-danger" href="{% url 'shop:delete_product_batch' product.pk %}" onclick="return confirm('Are you sure you want to delete this?')" >Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                    <tr><td>No Products Data</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
        </div>  <!-- /.col-lg-8 -->

        
    </div>
</div>
{% endblock content %}

shop/templates/shop/view_products_detail.html
{% extends 'base/base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title"><h3>{% for product in productName %} {{ product.product }} {% endfor %} View</h3>   <a href="{% url 'shop:add_product_packing' %}"> Add New Packing +</a>  
                        <a style="padding-left: 50px;" href="{% url 'shop:add_product_batch' %}"> Add New Batch +</a>
                    </h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">#</th>
                                    <th>Product Name</th>
                                    <th>Batch No.</th>
                                    <th>Packing</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if products_list %}
                                {% for product in products_list %}
                                <tr>
                                    <td class="serial">{{ forloop.counter }}</td>
                                    <td>{{ product.batch_no.product }}</td>
                                    <td>{{ product.batch_no.batch_no }}</td>
                                    <td>{{ product.packing }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.price }}</td>
                                    
                                    <td>
                                        <a class="btn btn-primary" href="{% url 'shop:edit_product_packing' product.pk %}" >Edit</a>
                                        <a class="btn btn-danger" href="{% url 'shop:delete_product_packing' product.pk %}" onclick="return confirm('Are you sure you want to delete this?')" >Delete</a>
                                        
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                    <tr><td>No Products Data</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
        </div>  <!-- /.col-lg-8 -->

        
    </div>
</div>
{% endblock content %}

shop/templates/shop/view_products_packing.html
{% extends 'base/base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Packing <button type="button" class="btn" style="color:white; "><a href="{% url 'shop:add_product_packing' %}"> Add New +</a> </button> </h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">#</th>
                                    <th>Product Name</th>
                                    <th>Batch No.</th>
                                    <th>Packing</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if products_list %}
                                {% for product in products_list %}
                                <tr>
                                    <td class="serial">{{ forloop.counter }}</td>
                                    <td><a class="btn btn-primary" href="{% url 'shop:product_detail_view' product.batch_no.product.id %}" >{{ product.batch_no.product }}</a></td>
                                    <td>{{ product.batch_no.batch_no }}</td>
                                    <td>{{ product.packing }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.price }}</td>
                                    
                                    <td>
                                        <a class="btn btn-primary" href="{% url 'shop:edit_product_packing' product.pk %}" >Edit</a>
                                        <a class="btn btn-danger" href="{% url 'shop:delete_product_packing' product.pk %}" onclick="return confirm('Are you sure you want to delete this?')" >Delete</a>
                                        
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                    <tr><td>No Products Data</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
        </div>  <!-- /.col-lg-8 -->

        
    </div>
</div>
{% endblock content %}