mysitetest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('index', views.index, name='index'),
    path('bill', views.add_bill, name='bill'),
    path('billtest', views.add_billtest, name='billtest'),
    path('', views.dashboard, name='dashboard'),
    path('add_customer', views.add_customer, name='add_customer'),
    path('add_product_packing', views.add_product_packing, name='add_product_packing'),
    path('add_product', views.add_product, name='add_product'),
    path('add_product_ingredient', views.add_product_ingredient, name='add_product_ingredient'),
    path('add_product_hsn_code', views.add_product_hsn_code, name='add_product_hsn_code'),
    path('add_product_batch', views.add_product_batch, name='add_product_batch'),
    path('edit_customer/<int:pk>', views.edit_customer, name='edit_customer'),
    path('edit_ingredient/<int:pk>', views.edit_ingredient, name='edit_ingredient'),
    path('edit_hsn_code/<int:pk>', views.edit_hsn_code, name='edit_hsn_code'),
    path('edit_product_packing/<int:pk>', views.edit_product_packing, name='edit_product_packing'),
    path('edit_product/<int:pk>', views.edit_product, name='edit_product'),
    path('edit_product_batch/<int:pk>', views.edit_product_batch, name='edit_product_batch'),
    path('delete_ingredient/<int:pk>', views.delete_ingredient, name='delete_ingredient'),
    path('delete_hsn_code/<int:pk>', views.delete_hsn_code, name='delete_hsn_code'),
    path('delete_customers/<int:pk>', views.delete_customers, name='delete_customers'),
    path('delete_product_batch/<int:pk>', views.delete_product_batch, name='delete_product_batch'),
    path('delete_product_packing/<int:pk>', views.delete_product_packing, name='delete_product_packing'),
    path('delete_product/<int:pk>', views.delete_product, name='delete_product'),
    path('delete_order/<int:pk>', views.delete_order, name='delete_order'),
    path('customers', views.customers, name='customers'),
    path('product_packing', views.product_packing, name='product_packing'),
    path('product_detail_view/<int:product_id>', views.product_detail_view, name='product_detail_view'),
    path('product', views.product, name='product'),
    path('product_ingredient', views.product_ingredient, name='product_ingredient'),
    path('product_hsn_code', views.product_hsn_code, name='product_hsn_code'),
    path('product_batch', views.product_batch, name='product_batch'),
    path('expired_product', views.expired_product, name='expired_product'),
    path('show/<int:purchaseno>', views.show, name='show'),
    path('edit/<int:purchaseno>/<int:customer_id>', views.edit_billtest_final, name='edit'),
]

shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from .models import Product,ProductDetailBatch,CustomerDetail,Bill,BillItems,BillItemsTest, BillTest2, BillItemsTest2,Ingredient, ProductBatch,HSNCode
from .forms import BillForm,BillItemsForm,BillItemsFormset,BillItemsFormsetTest, CustomerDetailForm,ProductDetailBatchForm, IngredientForm, ProductForm, ProductBatchForm,HSNCodeForm


def index(request):
    products_list = ProductDetailBatch.objects.all()
    customers_list = CustomerDetail.objects.all()
    bills_list = BillTest2.objects.select_related().all()
    bill_items = BillItemsTest2.objects.select_related().all()
    context = {'products_list': products_list, 'customers_list': customers_list, 'bills_list': bills_list, 'bill_items': bill_items}
    return render(request, 'shop/index.html', context)


# from django.forms.formsets import formset_factory

def add_bill(request):
    # BillItemsFormSet = formset_factory(BillItemsForm, extra=1, min_num=1, validate_min=True)
    customers_list = CustomerDetail.objects.all()
    if request.method == 'POST':
        form = BillForm(request.POST)
        formset = BillItemsFormset(request.POST)
        if all([form.is_valid(), formset.is_valid()]):
            bill = form.save()
            for inline_form in formset:
                if inline_form.cleaned_data:
                    billitems = inline_form.save(commit=False)
                    billitems.purchaseno = bill
                    billitems.save()
            return redirect('shop:index')
        else:
            print('form is not valid',form,formset)
    else:
        form = BillForm(request.GET or None)
        formset = BillItemsFormset(queryset=BillItems.objects.none())

    return render(request, 'shop/add_bill.html', {'form': form,
                                                   'formset': formset, 'customers': customers_list})

def add_billtest(request):
    # BillItemsFormSet = formset_factory(BillItemsForm, extra=1, min_num=1, validate_min=True)
    customers_list = CustomerDetail.objects.all()
    if request.method == 'POST':
        form = BillForm(request.POST)
        formset = BillItemsFormsetTest(request.POST)
        if all([form.is_valid(), formset.is_valid()]):
            bill = form.save()
            products_list = ProductDetailBatch.objects.all()
            purchase_no = -1
            for inline_form in formset:
                if inline_form.cleaned_data:
                    billitems = inline_form.save(commit=False)
                    billitems.purchaseno = bill
                    purchase_no = billitems.purchaseno.purchaseno
                    isFound = False
                    pro_pk = 0
                    print('purchaseno:',billitems.purchaseno,'billitems:',billitems.productName, 'productList:', products_list)
                    for pro in products_list:
                        if pro == billitems.productName and pro.quantity >= billitems.productQuantity:
                            isFound = True
                            pro_pk = pro.pk
                            print('isFound:True', 'pro_pk:', pro_pk)
                            billitems.productBatch = pro.batch_no.batch_no
                            billitems.productPacking = pro.packing
                            billitems.productPrice = pro.price
                            billitems.productTotalPrice = float(pro.price) * int(billitems.productQuantity)
                            break
                    if isFound:
                        productObj = ProductDetailBatch.objects.get(pk = pro_pk)
                        productObj.quantity -= billitems.productQuantity
                        print('productObj:', productObj, productObj.quantity)
                        billitems.save()
                        productObj.save()
                    else:
                        billObj = BillTest2.objects.get(purchaseno=bill.purchaseno)
                        billObj.delete()
                        return redirect('shop:product_packing')
            return redirect('shop:show', purchase_no)
        else:
            print('form is not valid',form,formset)
    else:
        form = BillForm(request.GET or None)
        formset = BillItemsFormsetTest(queryset=BillItems.objects.none())

    return render(request, 'shop/add_bill.html', {'form': form,
                                                   'formset': formset, 'customers': customers_list})


def show(request,purchaseno):
    bills_list = BillTest2.objects.select_related().all().filter(purchaseno=purchaseno)
    bill_items = BillItemsTest2.objects.select_related().all().filter(purchaseno=purchaseno)
    totalamount = 0
    totalamount_without_tax = 0
    total_tax = 0
    from .templatetags.calculate_tax import without_tax, tax
    for item in bill_items:
        totalamount += item.productTotalPrice
        totalamount_without_tax += without_tax(item.productTotalPrice, item.productName.batch_no.product.hsn_code.rate)
        total_tax += tax(item.productTotalPrice, item.productName.batch_no.product.hsn_code.rate)

    context = {'bills_list': bills_list, 'bill_items': bill_items, 'totalamount': totalamount, 'totalamount_without_tax': totalamount_without_tax, 'total_tax': total_tax}
    return render(request, 'shop/show.html', context)

def edit_billtest(request, purchaseno,customer_id):
    # BillItemsFormSet = formset_factory(BillItemsForm, extra=1, min_num=1, validate_min=True)
    bills = BillTest2.objects.get(purchaseno=purchaseno)
    bill_items = BillItemsTest2.objects.select_related().all().filter(purchaseno=purchaseno)
    customers_list = CustomerDetail.objects.all()
    if request.method == 'POST':
        form = BillForm(request.POST, instance = bills)
        formset = BillItemsFormsetTest(request.POST, queryset=bill_items)
        if all([form.is_valid(), formset.is_valid()]):
            bill = form.save()
            products_list = ProductDetailBatch.objects.all()
            purchase_no = -1
            for inline_form in formset:
                if inline_form.cleaned_data:
                    billitems = inline_form.save(commit=False)
                    billitems.purchaseno = bill
                    purchase_no = billitems.purchaseno.purchaseno
                    print('purchaseno:',billitems.purchaseno,'billitems:',billitems.productName, 'productList:', products_list)
                    for pro in products_list:
                        if pro == billitems.productName:
                            billitems.productBatch = pro.batch_no.batch_no
                            billitems.productPacking = pro.packing
                            billitems.productPrice = pro.price
                            billitems.productTotalPrice = float(pro.price) * int(billitems.productQuantity)
                            break
                    billitems.save()
            return redirect('shop:show', purchase_no)
        else:
            print('form is not valid',form.errors,formset.errors)
    else:
        form = BillForm(instance = bills)
        formset = BillItemsFormsetTest(queryset=bill_items)

    return render(request, 'shop/edit_bill.html', {'form': form,
                                                   'formset': formset, 'customers': customers_list})

def dashboard(request):
    total_product = Product.objects.count()
    total_buyer = CustomerDetail.objects.count()
    total_order = BillTest2.objects.count()
    orders = BillTest2.objects.select_related().all().order_by('-purchaseno')
    from datetime import date
    expired = ProductBatch.objects.all().filter(expirydate__lte = date.today()).count()
    context = {
        'product': total_product,
        'buyer': total_buyer,
        'order': total_order,
        'orders': orders,
        'expired': expired
    }
    return render(request, 'shop/dashboard.html', context)

def add_customer(request):
    if request.method == 'POST':
        form = CustomerDetailForm(request.POST)
        if form.is_valid():
            customer = form.save()
            return redirect('shop:dashboard')
        else:
            print('form is not valid',form)
    else:
        form = CustomerDetailForm(request.GET or None)
    return render(request, 'shop/add_customer.html', {'form': form, 'btn_add_edit': 'Create'})

def customers(request):
    customers_list = CustomerDetail.objects.all()
    context = {'customers_list': customers_list}
    return render(request, 'shop/view_customer.html', context)

def edit_customer(request, pk):
    customer = CustomerDetail.objects.get(pk=pk)
    if request.method == 'POST':
        form = CustomerDetailForm(request.POST,instance = customer)
        if form.is_valid():
            customer = form.save()
            return redirect('shop:customers')
        else:
            print('form is not valid',form)
    else:
        form = CustomerDetailForm(instance = customer)
    return render(request, 'shop/add_customer.html', {'form': form, 'btn_add_edit': 'Update'})

def product_packing(request):
    products_list = ProductDetailBatch.objects.all()
    context = {'products_list': products_list}
    return render(request, 'shop/view_products_packing.html', context)

def add_product_packing(request):
    if request.method == 'POST':
        form = ProductDetailBatchForm(request.POST)
        if form.is_valid():
            product = form.save()
            return redirect('shop:product_packing')
        else:
            print('form is not valid',form)
    else:
        form = ProductDetailBatchForm(request.GET or None)
    return render(request, 'shop/add_product_packing.html', {'form': form, 'btn_add_edit': 'Create'})

def edit_product_packing(request, pk):
    productbatch = ProductDetailBatch.objects.get(pk=pk)
    if request.method == 'POST':

shop/templates/base/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="Agro Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lib/datatable/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

   <style>
    #weatherWidget .currentDesc {
        color: #ffffff!important;
    }
        .traffic-chart {
            min-height: 335px;
        }
        #flotPie1  {
            height: 150px;
        }
        #flotPie1 td {
            padding:3px;
        }
        #flotPie1 table {
            top: 20px!important;
            right: -10px!important;
        }
        .chart-container {
            display: table;
            min-width: 270px ;
            text-align: left;
            padding-top: 10px;
            padding-bottom: 10px;
        }
        #flotLine5  {
             height: 105px;
        }

        #flotBarChart {
            height: 150px;
        }
        #cellPaiChart{
            height: 160px;
        }

    </style>
</head>

<body>
    <!-- Left Panel -->
    {% include 'base/sidebar.html' %}
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        {% include 'base/navbar.html' %}

        {% block breadcrumbs %}
        
        {% endblock breadcrumbs %}
        <!-- /#header -->
        <!-- Content -->
        <div class="content">
            <!-- Animated -->
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert {{ message.tags }} text-center"{% endif %}>
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="animated fadeIn">
                {% block content %}
                {% endblock content %}
            </div>
            <!-- .animated -->
        </div>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        {% include 'base/footer.html' %}
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!--  Chart js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

    <!--Chartist Chart-->
    <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="{% static 'assets/js/init/weather-init.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>


    <!--Local Stuff-->
    <script>
        jQuery(document).ready(function($) {
            "use strict";

            // Pie chart flotPie1
            var piedata = [
                { label: "Desktop visits", data: [[1,32]], color: '#5c6bc0'},
                { label: "Tab visits", data: [[1,33]], color: '#ef5350'},
                { label: "Mobile visits", data: [[1,35]], color: '#66bb6a'}
            ];

            $.plot('#flotPie1', piedata, {
                series: {
                    pie: {
                        show: true,
                        radius: 1,
                        innerRadius: 0.65,
                        label: {
                            show: true,
                            radius: 2/3,
                            threshold: 1
                        },
                        stroke: {
                            width: 0
                        }
                    }
                },
                grid: {
                    hoverable: true,
                    clickable: true
                }
            });
            // Pie chart flotPie1  End
            // cellPaiChart
            var cellPaiChart = [
                { label: "Direct Sell", data: [[1,65]], color: '#5b83de'},
                { label: "Channel Sell", data: [[1,35]], color: '#00bfa5'}
            ];
            $.plot('#cellPaiChart', cellPaiChart, {
                series: {
                    pie: {
                        show: true,
                        stroke: {
                            width: 0
                        }
                    }
                },
                legend: {
                    show: false
                },grid: {
                    hoverable: true,
                    clickable: true
                }

            });
            // cellPaiChart End
            // Line Chart  #flotLine5
            var newCust = [[0, 3], [1, 5], [2,4], [3, 7], [4, 9], [5, 3], [6, 6], [7, 4], [8, 10]];

            var plot = $.plot($('#flotLine5'),[{
                data: newCust,
                label: 'New Data Flow',
                color: '#fff'
            }],
            {
                series: {
                    lines: {
                        show: true,
                        lineColor: '#fff',
                        lineWidth: 2
                    },
                    points: {
                        show: true,
                        fill: true,
                        fillColor: "#ffffff",
                        symbol: "circle",
                        radius: 3
                    },
                    shadowSize: 0
                },
                points: {
                    show: true,
                },
                legend: {
                    show: false
                },
                grid: {
                    show: false
                }
            });
            // Line Chart  #flotLine5 End
            // Traffic Chart using chartist
            if ($('#traffic-chart').length) {
                var chart = new Chartist.Line('#traffic-chart', {
                  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                  series: [
                  [0, 18000, 35000,  25000,  22000,  0],
                  [0, 33000, 15000,  20000,  15000,  300],
                  [0, 15000, 28000,  15000,  30000,  5000]
                  ]
              }, {
                  low: 0,
                  showArea: true,
                  showLine: false,
                  showPoint: false,
                  fullWidth: true,
                  axisX: {
                    showGrid: true
                }
            });

                chart.on('draw', function(data) {
                    if(data.type === 'line' || data.type === 'area') {
                        data.element.animate({
                            d: {
                                begin: 2000 * data.index,
                                dur: 2000,
                                from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
                                to: data.path.clone().stringify(),
                                easing: Chartist.Svg.Easing.easeOutQuint
                            }
                        });
                    }
                });
            }
            // Traffic Chart using chartist End
            //Traffic chart chart-js
            if ($('#TrafficChart').length) {
                var ctx = document.getElementById( "TrafficChart" );
                ctx.height = 150;
                var myChart = new Chart( ctx, {
                    type: 'line',
                    data: {
                        labels: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul" ],
                        datasets: [
                        {
                            label: "Visit",
                            borderColor: "rgba(4, 73, 203,.09)",
                            borderWidth: "1",
                            backgroundColor: "rgba(4, 73, 203,.5)",
                            data: [ 0, 2900, 5000, 3300, 6000, 3250, 0 ]
                        },
                        {
                            label: "Bounce",
                            borderColor: "rgba(245, 23, 66, 0.9)",
                            borderWidth: "1",
                            backgroundColor: "rgba(245, 23, 66,.5)",
                            pointHighlightStroke: "rgba(245, 23, 66,.5)",
                            data: [ 0, 4200, 4500, 1600, 4200, 1500, 4000 ]
                        },
                        {
                            label: "Targeted",
                            borderColor: "rgba(40, 169, 46, 0.9)",
                            borderWidth: "1",
                            backgroundColor: "rgba(40, 169, 46, .5)",
                            pointHighlightStroke: "rgba(40, 169, 46,.5)",
                            data: [1000, 5200, 3600, 2600, 4200, 5300, 0 ]
                        }
                        ]
                    },
                    options: {
                        responsive: true,
                        tooltips: {
                            mode: 'index',
                            intersect: false
                        },
                        hover: {
                            mode: 'nearest',
                            intersect: true
                        }

                    }
                } );
            }
            //Traffic chart chart-js  End
            // Bar Chart #flotBarChart
            $.plot("#flotBarChart", [{
                data: [[0, 18], [2, 8], [4, 5], [6, 13],[8,5], [10,7],[12,4], [14,6],[16,15], [18, 9],[20,17], [22,7],[24,4], [26,9],[28,11]],
                bars: {
                    show: true,
                    lineWidth: 0,
                    fillColor: '#ffffff8a'
                }
            }], {
                grid: {
                    show: false
                }
            });
            // Bar Chart #flotBarChart End
        });
    </script>
</body>
</html>

shop/templates/base/footer.html
<footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                Copyright &copy; {% now "Y"%} Management Admin
            </div>
            <div class="col-sm-6 text-right">
                Developed by <a href="https://github.com/Vasanth272001">Vasanth Kumar</a>
            </div>
        </div>
    </div>
</footer>

shop/templates/base/sidebar.html
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'shop:dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                </li>
                <li class="menu-title">My Store</li><!-- /.menu-title -->
                

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Customer</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:add_customer' %}">Add</a></li>
                        <li><i class="fa fa-th"></i><a href="{% url 'shop:customers' %}">View</a></li>
                    </ul>
                </li>


                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-product-hunt"></i>Product</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:add_product_hsn_code' %}">Add HSN Code</a></li>
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:add_product_ingredient' %}">Add Ingredient</a></li>
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:add_product' %}">Add Product</a></li>
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:add_product_batch' %}">Add Batch</a></li>
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:add_product_packing' %}">Add Packing</a></li>
                        
                        <li><i class="fa fa-th" style="color:rgb(108, 114, 170)"></i><a href="{% url 'shop:product_hsn_code' %}">HSN Code</a></li>
                        <li><i class="fa fa-th" style="color:rgb(108, 114, 170)"></i><a href="{% url 'shop:product_ingredient' %}">Ingredients</a></li>
                        <li><i class="fa fa-th" style="color:rgb(108, 114, 170)"></i><a href="{% url 'shop:product' %}">Product</a></li>
                        <li><i class="fa fa-th" style="color:rgb(108, 114, 170)"></i><a href="{% url 'shop:product_batch' %}">Product Batch</a></li>
                        <li><i class="fa fa-th" style="color:rgb(108, 114, 170)"></i><a href="{% url 'shop:product_packing' %}">Product Packing</a></li>
                        <li><i class="fa fa-th" style="color:orangered"></i><a href="{% url 'shop:expired_product' %}">Expired Product Batch</a></li>
                        
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-cart-plus"></i>Order</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-id-card-o"></i><a href="{% url 'shop:billtest' %}">Add</a></li>
                        <li><i class="fa fa-th"></i><a href="{% url 'shop:dashboard' %}">View</a></li>
                    </ul>
                </li>

                
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>